import { NextRequest,NextResponse } from "next/server";
import { Firestore,Timestamp } from "@google-cloud/firestore";
import { Storage } from "@google-cloud/storage";
import { uuidv7 } from "uuidv7";
import { requireAuthenticatedUser } from "@/lib/auth/server";
import { apiError } from "@/lib/api/errors";
import { uploadMetadataSchema,safeOriginalName } from "@/lib/documents/security";
import { requestId,requireSameOrigin } from "@/lib/api/request";
import { requireCloudConfiguration } from "@/lib/env";
export const runtime="nodejs";
export async function POST(request:NextRequest){const id=requestId(request);try{requireSameOrigin(request);const user=await requireAuthenticatedUser(request);const input=uploadMetadataSchema.parse(await request.json());const env=requireCloudConfiguration();const db=new Firestore({projectId:env.GCP_PROJECT_ID,databaseId:env.FIRESTORE_DATABASE_ID});const caseRef=db.doc(`cases/${input.caseId}`);const caseSnapshot=await caseRef.get();if(!caseSnapshot.exists||caseSnapshot.get("owner_uid")!==user.uid)throw Object.assign(new Error("Case not found"),{status:404});const documentId=uuidv7();const objectName=`incoming/${input.caseId}/${documentId}/original`;const now=Timestamp.now();await caseRef.collection("documents").doc(documentId).create({documentId,clientId:caseSnapshot.get("clientId"),caseId:input.caseId,assessmentYear:input.assessmentYear,originalObject:objectName,processedObject:null,originalFilename:safeOriginalName(input.fileName),declaredSize:input.size,declaredMimeType:input.mimeType,renamedFilename:null,documentType:null,issuer:null,documentDate:null,checksumSha256:null,processingStatus:"AWAITING_UPLOAD",confidence:null,evidenceStatus:"UNASSESSED",gcsGeneration:"PENDING",processingVersion:"doc-agent-1.0.0",createdAt:now,processedAt:null,owner_uid:user.uid});const [uploadUrl]=await new Storage({projectId:env.GCP_PROJECT_ID}).bucket(env.GCS_QUARANTINE_BUCKET).file(objectName).getSignedUrl({version:"v4",action:"write",expires:Date.now()+env.SIGNED_URL_TTL_SECONDS*1000,contentType:input.mimeType});return NextResponse.json({documentId,uploadUrl,method:"PUT",requiredHeaders:{"content-type":input.mimeType},expiresInSeconds:env.SIGNED_URL_TTL_SECONDS,status:"AWAITING_UPLOAD"},{status:201})}catch(error){return apiError(error,id)}}
