export const caseStatuses = [
  "DRAFT", "PROFILE_COMPLETE", "INCOME_UPLOADED", "INCOME_PROCESSING", "TAX_CALCULATED",
  "DEDUCTIONS_IN_PROGRESS", "DEDUCTIONS_CALCULATED", "EVIDENCE_REVIEW", "PREFERENCE_CONFIRMED",
  "SUBMITTED_FOR_REVIEW", "REVIEW_IN_PROGRESS", "CLIENT_ACTION_REQUIRED", "READY_FOR_FILING", "FILED", "COMPLETED"
] as const;
export type CaseStatus = (typeof caseStatuses)[number];

const transitions: Record<CaseStatus, readonly CaseStatus[]> = {
  DRAFT: ["PROFILE_COMPLETE"], PROFILE_COMPLETE: ["INCOME_UPLOADED"], INCOME_UPLOADED: ["INCOME_PROCESSING"],
  INCOME_PROCESSING: ["TAX_CALCULATED", "CLIENT_ACTION_REQUIRED"], TAX_CALCULATED: ["DEDUCTIONS_IN_PROGRESS"],
  DEDUCTIONS_IN_PROGRESS: ["DEDUCTIONS_CALCULATED", "CLIENT_ACTION_REQUIRED"], DEDUCTIONS_CALCULATED: ["EVIDENCE_REVIEW"],
  EVIDENCE_REVIEW: ["PREFERENCE_CONFIRMED", "CLIENT_ACTION_REQUIRED"], PREFERENCE_CONFIRMED: ["SUBMITTED_FOR_REVIEW"],
  SUBMITTED_FOR_REVIEW: ["REVIEW_IN_PROGRESS"], REVIEW_IN_PROGRESS: ["CLIENT_ACTION_REQUIRED", "READY_FOR_FILING"],
  CLIENT_ACTION_REQUIRED: ["INCOME_PROCESSING", "DEDUCTIONS_IN_PROGRESS", "SUBMITTED_FOR_REVIEW"],
  READY_FOR_FILING: ["FILED"], FILED: ["COMPLETED"], COMPLETED: []
};

export function canTransition(from: CaseStatus, to: CaseStatus): boolean { return transitions[from].includes(to); }
