import type {Classification,DocumentType,ProvenanceField} from "../shared/types.js";
import {extractIncomeFields} from "../extraction/income-field-extractor.js";
import {extractDeductionFields} from "../extraction/deduction-field-extractor.js";
const rules:[DocumentType,RegExp,string][]=[
 ["AIS",/annual information statement|\bais\b/i,"AIS_MARKER"],["TIS",/taxpayer information summary|\btis\b/i,"TIS_MARKER"],["FORM_26AS",/form\s*26as/i,"26AS_MARKER"],["FORM_10BE",/form\s*10be/i,"10BE_MARKER"],["FORM_16",/form\s*no\.?\s*16|certificate under section 203/i,"FORM16_MARKER"],["SALARY_SLIP",/salary slip|payslip|net pay/i,"PAYSLIP_MARKER"],
 ["HEALTH_INSURANCE_PREMIUM",/health insurance|mediclaim|medical insurance premium/i,"HEALTH_POLICY_MARKER"],["LIFE_INSURANCE_PREMIUM",/life insurance premium|lic premium/i,"LIFE_POLICY_MARKER"],["TUITION_FEE_RECEIPT",/tuition fee|school fee/i,"TUITION_MARKER"],["NPS_CONTRIBUTION",/national pension system|\bpran\b|nps contribution/i,"NPS_MARKER"],["PPF",/public provident fund|\bppf\b/i,"PPF_MARKER"],["EPF",/employees provident fund|\bepf\b/i,"EPF_MARKER"],["ELSS",/equity linked savings scheme|\belss\b/i,"ELSS_MARKER"],["NSC",/national savings certificate|\bnsc\b/i,"NSC_MARKER"],["HOME_LOAN_PRINCIPAL_CERTIFICATE",/home loan principal|principal repayment/i,"HOME_PRINCIPAL_MARKER"],["EDUCATION_LOAN_INTEREST",/education loan interest|section\s*80e/i,"EDUCATION_LOAN_MARKER"],["BANK_INTEREST_CERTIFICATE",/interest certificate|interest earned/i,"INTEREST_MARKER"],["DONATION_80G",/80g|donation receipt/i,"80G_MARKER"],["TAX_PAYMENT_CHALLAN",/challan|cin\b|bsr code/i,"CHALLAN_MARKER"]
];
const nullField=(documentId:string):ProvenanceField=>({name:"document_total",value:null,confidence:0,sourceDocumentId:documentId,sourcePage:null,sourceRegion:null,extractionMethod:"DETERMINISTIC",extractorName:"deterministic-classifier",extractorVersion:"1.0.0",validated:false,reviewStatus:"DETECTED"});
export function classifyDeterministically(text:string,filename:string,documentId:string,assessmentYear:string):Classification{const source=`${filename}\n${text.slice(0,200_000)}`,hit=rules.find(([,rule])=>rule.test(source)),documentType=hit?.[0]??"UNKNOWN",issuer=/employer(?:'s)?\s+(?:name)?\s*[:\-]\s*([^\r\n]{3,80})/i.exec(text)?.[1]?.trim()??null,date=/(20\d{2})[-\/]([01]\d)[-\/]([0-3]\d)/.exec(text);return {documentType,issuer,documentDate:date?`${date[1]}-${date[2]}-${date[3]}`:null,financialYear:null,assessmentYear,candidateTaxSections:[],confidence:documentType==="FORM_16"?.96:documentType!=="UNKNOWN"?.9:.25,rationaleCodes:hit?[hit[2]]:["NO_RELIABLE_MARKER"],fields:[nullField(documentId),...extractIncomeFields(text,documentId,documentType),...extractDeductionFields(text,documentId,documentType)]};}
