import {describe,expect,it} from "vitest";
import {DocumentPipeline} from "../src/pipeline/document-pipeline.js";
import {MemoryObjectStore,MemoryRepositories} from "../src/storage/repositories.js";
import {LogMetrics} from "../src/observability/metrics.js";
import type {Config} from "../src/shared/config.js";
import type {DocumentMetadata,PipelineEvent} from "../src/shared/types.js";
const config:Config={PORT:8080,APP_ENV:"local",GCP_PROJECT_ID:"test",GCS_QUARANTINE_BUCKET:"quarantine",GCS_DOCUMENT_BUCKET:"documents",GCS_EXPORT_BUCKET:"exports",BQ_DATASET:"test",DOCUMENT_AI_LOCATION:"asia-south1",MAX_FILE_BYTES:25_000_000,PROCESSING_VERSION:"doc-agent-1.0.0",AUTO_PROCESS_THRESHOLD:.9,REVIEW_THRESHOLD:.75};
const event=(documentId:string,mime="application/pdf"):PipelineEvent=>({eventId:"evt-1",bucket:"quarantine",objectName:`incoming/case-1/${documentId}/original`,generation:"1",contentType:mime,size:100,caseId:"case-1",documentId});
const metadata=(documentId:string,filename:string):DocumentMetadata=>({documentId,clientId:"019abc00-a72d-91ff-8000-000000000001",caseId:"case-1",assessmentYear:"AY2026-27",originalObject:`incoming/case-1/${documentId}/original`,processedObject:null,originalFilename:filename,renamedFilename:null,documentType:null,issuer:null,documentDate:null,checksumSha256:null,processingStatus:"UPLOADED",confidence:null,evidenceStatus:"UNASSESSED",gcsGeneration:"1",processingVersion:"doc-agent-1.0.0",createdAt:new Date().toISOString(),processedAt:null});
describe("pipeline",()=>{
 it("preserves original, classifies, renames, stores and becomes READY idempotently",async()=>{const repo=new MemoryRepositories();const objects=new MemoryObjectStore();const id="doc-form16";await repo.update(metadata(id,"random_document_8734.pdf"));const pdf=Buffer.from("%PDF-1.7\nFORM NO. 16\nEmployer Name: TEST EMPLOYER\n2026-03-31\n/Type /Page\n%%EOF");objects.putOriginal(`incoming/case-1/${id}/original`,pdf);const pipeline=new DocumentPipeline({config,objects,documents:repo,events:repo,metrics:new LogMetrics()});const result=await pipeline.process(event(id));expect(result?.processingStatus).toBe("READY");expect(result?.renamedFilename).toContain("FORM16_TESTEMPLOYER_20260331_01.pdf");expect(result?.processedObject).toContain("/AY2026-27/income/");expect(objects.objects.get(`quarantine/incoming/case-1/${id}/original`)).toEqual(pdf);expect(objects.objects.get(`documents/${result?.processedObject}`)).toEqual(pdf);expect(await pipeline.process(event(id))).toEqual(result)});
 it("processes structured AIS without asking for PAN or DOB",async()=>{const repo=new MemoryRepositories();const objects=new MemoryObjectStore();const id="doc-ais";await repo.update(metadata(id,"ais.json"));const json=Buffer.from(JSON.stringify({records:[{description:"Salary",amount:"1000"},{description:"TDS",amount:"100"}]}));objects.putOriginal(`incoming/case-1/${id}/original`,json);const pipeline=new DocumentPipeline({config,objects,documents:repo,events:repo,metrics:new LogMetrics()});const result=await pipeline.process(event(id,"application/json"));expect(result?.documentType).toBe("AIS");expect(result?.processingStatus).toBe("READY");expect(repo.records.map(r=>r.category)).toEqual(["SALARY","TDS"])});
});
